
project_id = "mmzlufnvxzqdkreatybs"

[build]
cmd = "deno task bundle"
[[build.engines]]
name = "deno"
version = "1.37.1"

[deploy]
allow_list = ["puppeteer"]

[[deploy.imports]]
name = "chrome"
path = "https://deno.land/x/puppeteer@16.2.0/vendor/chrome-linux/chrome"

[http]
timeout = 30
