
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smhqhrdkdrhfheteieqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtaHFocmRrZHJoZmhldGVpZXFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2NjczNDksImV4cCI6MjA1NjI0MzM0OX0.uhK0nfn8qZO-2ZZKhWa1WBn4-nDsq1qNCELuJYdkGEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      fetch: (...args) => {
        // Add custom fetch options like timeouts
        const [url, options] = args;
        return fetch(url, {
          ...options,
          signal: options?.signal || (new AbortController().signal),
        });
      }
    }
  }
);
