// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmzlufnvxzqdkreatybs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1temx1Zm52eHpxZGtyZWF0eWJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1MzU5NTMsImV4cCI6MjA1MzExMTk1M30.4-iIKcLKRYxvVlWGDalxcg57lMuIyMkilIBIo0ue_Cg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);